
all:
	g++ -c basic_win32.cpp -I ../../ -o basic.o
	g++ -shared -g -o ../basic.dll \
    -Wl,--export-all-symbols \
    -Wl,--enable-auto-import \
    -Wl,--whole-archive basic.o \
    -Wl,--no-whole-archive ../libsol.a