
all:
	g++ -Wall **/*.cpp app.cpp -lwsock32 -o webserver 2>make.log
	@echo "See make.log for output."

lib:
	g++ -c http/request.cpp http/response.cpp utils/ioutils.cpp utils/stringutils.cpp
	ar rvs modules/libsol.a request.o response.o ioutils.o stringutils.o
	rm request.o response.o ioutils.o stringutils.o

modules: lib
	mingw32-make -C modules/dynwindows
	mingw32-make -C modules/hello
