
all:
	g++ -c hello_win32.cpp -o hello.o
	g++ -shared -g -o ../hello.dll \
    -Wl,--export-all-symbols \
    -Wl,--enable-auto-import \
    -Wl,--whole-archive hello.o \
    -Wl,--no-whole-archive ../libsol.a